name: ✨ 功能请求
description: 提出新功能或改进建议
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              感谢您的建议！您的想法对项目发展非常重要。

    - type: dropdown
      id: script
      attributes:
          label: 目标脚本
          description: 请选择您希望添加功能的脚本
          options:
              - Gemini Helper
              - Coomer 佬友严选
              - 通用 / 新脚本建议
      validations:
          required: true

    - type: dropdown
      id: site
      attributes:
          label: 目标站点
          description: 请选择希望支持的站点
          options:
              - gemini.google.com（Gemini）
              - business.gemini.google（Gemini Enterprise）
              - 其他（请在下方说明）
              - 不适用 / 通用功能
      validations:
          required: true

    - type: input
      id: site_other
      attributes:
          label: 其他站点（可选）
          description: 如选择"其他"，请在此填写站点地址
          placeholder: '例如: https://example.com'

    - type: dropdown
      id: request_type
      attributes:
          label: 请求类型
          description: 请选择请求的类型
          options:
              - 新功能
              - 现有功能改进
              - 性能优化
              - UI/UX 改进
              - 其他
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: 问题背景
          description: 请描述您希望解决的问题或痛点
          placeholder: |
              我在使用 [...] 功能时，经常遇到 [...] 的问题...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: 期望的解决方案
          description: 请清晰地描述您希望实现的功能
          placeholder: |
              我希望能够 [...]
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: 备选方案
          description: 您是否考虑过其他替代方案？
          placeholder: |
              其他可能的实现方式...

    - type: textarea
      id: mockup
      attributes:
          label: 设计草图（可选）
          description: 如果涉及 UI 变更，可以提供草图或参考示例
          placeholder: |
              拖拽或粘贴图片到这里...

    - type: textarea
      id: additional_context
      attributes:
          label: 其他信息
          description: 添加任何其他与该功能请求相关的上下文
          placeholder: |
              任何额外的背景信息或参考链接...

    - type: checkboxes
      id: checklist
      attributes:
          label: 提交前检查
          description: 请确认以下事项
          options:
              - label: 我已搜索过现有 Issues，确认没有类似的功能请求
                required: true
